name: Run tests

on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.3', '1.4', '1.5.0-beta1', 'nightly']
        os: [ubuntu-latest, macOS-latest]
        # empty entry for defaults
        xcode: [ '' ]
        cxxwrap: [ '' ]
        exclude:
        # remove some macOS tests to keep the total number small
          - os: macos-latest
            julia-version: '1.3'
          - os: macos-latest
            julia-version: 'nightly'
        # add a few extra tests: xcode 11.4 bug and legacy cxxwrap 0.9
        include:
          - xcode: '11.4'
            os: macos-latest
            julia-version: 1.4
          - cxxwrap: '0.9'
            os: ubuntu-latest
            julia-version: 1.4

      fail-fast: false

    steps:
      - uses: actions/checkout@v2.1.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Pin CxxWrap"
        if: matrix.cxxwrap != ''
        run: julia --project -e 'using Pkg; pkg"add CxxWrap@${{ matrix.cxxwrap }}"; pkg"pin CxxWrap";'
      - name: "set xcode"
        if: matrix.xcode != ''
        run: echo "::set-env name=DEVELOPER_DIR::/Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer"
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
